spring.application.name=PersonalTracker

# Tell Java exactly which database to talk to on your laptop or in production
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/personal_tracker_db}

# Credentials to prove it's you
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MySql@1234}

# Hibernate 'update' means Spring will automatically sync your Java 
# classes with MySQL tables every time you run the app.
spring.jpa.hibernate.ddl-auto=update

# Essential for Render deployment (port binding)
server.port=${PORT:8080}